// Highlighted sidebar items
export const NEW = [
  'Accordion Gallery',
  'Acid Squares',
  'Depth Carousel',
  'Depth Text',
  'Drift Wall',
  'Echo Text',
  'Elastic Mesh',
  'Fold Text',
  'Gradient Waves',
  'Halftone Reveal',
  'Light Tunnel',
  'Masked Heading',
  'Molten Metal',
  'Morph Slider',
  'Particle Text',
  'Ripple Distortion',
  'Scroll Expand',
  'Sliced Waves',
  'Split Flap Text',
  'Stroke Text',
  'Swarm Cursor',
  'Text Loop',
  'Topography',
  'Warp Text',
  'Web Threads',
  'CRT Warp',
  'Glow Cursor'
];
export const UPDATED = [];

// Used for main sidebar navigation
export const CATEGORIES = [
  {
    name: 'Get Started',
    subcategories: ['Introduction', 'Installation', 'MCP', 'Index']
  },
  {
    name: 'Text Animations',
    subcategories: [
      'Warp Text',
      'Text Loop',
      'Stroke Text',
      'Split Flap Text',
      'Particle Text',
      'Masked Heading',
      'Fold Text',
      'Echo Text',
      'Depth Text',
      'ASCII Text',
      'Blur Text',
      'Circular Text',
      'Count Up',
      'Curved Loop',
      'Decrypted Text',
      'Falling Text',
      'Fuzzy Text',
      'Glitch Text',
      'Gradient Text',
      'Rotating Text',
      'Scramble Text',
      'Scroll Float',
      'Scroll Reveal',
      'Scroll Velocity',
      'Shiny Text',
      'Shuffle',
      'Split Text',
      'Text Cursor',
      'Text Pressure',
      'Text Type',
      'True Focus',
      'Variable Proximity'
    ]
  },
  {
    name: 'Animations',
    subcategories: [
      'Glow Cursor',
      'Swarm Cursor',
      'Scroll Expand',
      'Ripple Distortion',
      'Halftone Reveal',
      'Elastic Mesh',
      'Animated Content',
      'Antigravity',
      'Blob Cursor',
      'Click Spark',
      'Crosshair',
      'Cubes',
      'Cursor Grid',
      'Electric Border',
      'Fade Content',
      'Ghost Cursor',
      'Glare Hover',
      'Gradual Blur',
      'Image Trail',
      'Laser Flow',
      'Logo Loop',
      'Magic Rings',
      'Magnet',
      'Magnet Lines',
      'Meta Balls',
      'Metallic Paint',
      'Noise',
      'Orbit Images',
      'Pixel Trail',
      'Pixel Transition',
      'Ribbons',
      'Shape Blur',
      'Splash Cursor',
      'Star Border',
      'Sticker Peel',
      'Strands',
      'Target Cursor'
    ]
  },
  {
    name: 'Components',
    subcategories: [
      'Morph Slider',
      'Drift Wall',
      'Depth Carousel',
      'Accordion Gallery',
      'Animated List',
      'Border Glow',
      'Bounce Cards',
      'Bubble Menu',
      'Card Nav',
      'Card Swap',
      'Carousel',
      'Chroma Grid',
      'Circular Gallery',
      'Curved Input',
      'Counter',
      'Decay Card',
      'Dock',
      'Dome Gallery',
      'Elastic Slider',
      'Flowing Menu',
      'Flying Posters',
      'Folder',
      'Glass Icons',
      'Glass Surface',
      'Gooey Nav',
      'Infinite Menu',
      'Line Sidebar',
      'Magic Bento',
      'Masonry',
      'Model Viewer',
      'Option Wheel',
      'Pill Nav',
      'Pixel Card',
      'Profile Card',
      'Reflective Card',
      'Scroll Stack',
      'Specular Button',
      'Spotlight Card',
      'Stack',
      'Staggered Menu',
      'Stepper',
      'Tilted Card'
    ]
  },
  {
    name: 'Backgrounds',
    subcategories: [
      'CRT Warp',
      'Web Threads',
      'Topography',
      'Sliced Waves',
      'Molten Metal',
      'Light Tunnel',
      'Gradient Waves',
      'Acid Squares',
      'Aurora',
      'Balatro',
      'Ballpit',
      'Beams',
      'Color Bends',
      'Dark Veil',
      'Dither',
      'Dot Field',
      'Dot Grid',
      'Evil Eye',
      'Faulty Terminal',
      'Ferrofluid',
      'Floating Lines',
      'Galaxy',
      'Gradient Blinds',
      'Grainient',
      'Grid Distortion',
      'Grid Motion',
      'Grid Scan',
      'Hyperspeed',
      'Iridescence',
      'Letter Glitch',
      'Light Pillar',
      'Light Rays',
      'Lightfall',
      'Lightning',
      'Line Waves',
      'Liquid Chrome',
      'Liquid Ether',
      'Orb',
      'Particles',
      'Pixel Blast',
      'Pixel Snow',
      'Plasma',
      'Plasma Wave',
      'Prism',
      'Prismatic Burst',
      'Radar',
      'Ripple Grid',
      'Shape Grid',
      'Side Rays',
      'Silk',
      'Soft Aurora',
      'Threads',
      'Waves'
    ]
  }
];

export const TOTAL_COMPONENTS = CATEGORIES.filter(category => category.name !== 'Get Started').reduce(
  (total, category) => total + category.subcategories.length,
  0
);

// Slug helpers (kebab-case used in URLs).
export const slug = (s: string) => s.replace(/\s+/g, '-').toLowerCase();
export const decodeLabel = (s: string) =>
  s
    .split('-')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
