// Highlighted sidebar items
export const NEW = [
  'Electric Logo',
  'Micro Slats',
  'Flex Carousel',
  'Tech Text',
  'Dither Veil',
  'Shredder',
  'Paper Crumple',
  'Tear Ticket',
  'Flip Card',
  'Branched Menu',
  'Folder Float',
  'Refine Frame',
  'Thought Line',
  'Voice Pill',
  'Slosh Gauge',
  'Prompt Bar',
  'Swipe Toast',
  'Sling Button',
  'Bell Toggle',
  'Call Chip',
  'Status Mark',
  'Glide Select',
  'Swipe Row',
  'Jelly Radio',
  'Comet Dial',
  'Wake Slider',
  'Code Slots',
  'Dodge Field',
  'Lattice Loader',
  'Scrub Field',
  'Fuse Button',
  'Warm Tooltip',
  'Slide Commit',
  'Rubber Segment',
  'Pulse Heart',
  'Spring Check',
  'Peek Rating',
  'Hold Button',
  'Squish Switch',
  'Shape Waves',
  'Aero Shards',
  'Ghost Fibers',
  'Infinite Spiral',
  'CRT Warp',
  'Glow Cursor',
  'Scanner',
  'Scroll Expand',
  'Ripple Distortion',
  'Depth Carousel',
  'Morph Slider',
  'Drift Wall',
  'Particle Text',
  'Split Flap Text',
  'Warp Text',
  'Depth Text',
  'Text Loop',
  'Molten Metal',
  'Gradient Waves',
  'Web Threads'
];
export const UPDATED = [];

// Used for main sidebar navigation
export const CATEGORIES = [
  {
    name: 'Get Started',
    subcategories: ['Introduction', 'Installation', 'MCP', 'Index']
  },
  {
    name: 'Text Animations',
    subcategories: [
      'Tech Text',
      'Warp Text',
      'Text Loop',
      'Stroke Text',
      'Split Flap Text',
      'Particle Text',
      'Masked Heading',
      'Fold Text',
      'Echo Text',
      'Depth Text',
      'ASCII Text',
      'Blur Text',
      'Circular Text',
      'Count Up',
      'Curved Loop',
      'Decrypted Text',
      'Falling Text',
      'Fuzzy Text',
      'Glitch Text',
      'Gradient Text',
      'Rotating Text',
      'Scramble Text',
      'Scroll Float',
      'Scroll Reveal',
      'Scroll Velocity',
      'Shiny Text',
      'Shuffle',
      'Split Text',
      'Text Cursor',
      'Text Pressure',
      'Text Type',
      'True Focus',
      'Variable Proximity'
    ]
  },
  {
    name: 'Animations',
    subcategories: [
      'Electric Logo',
      'Dither Veil',
      'Pixel Swap',
      'Glow Cursor',
      'Swarm Cursor',
      'Scroll Expand',
      'Ripple Distortion',
      'Halftone Reveal',
      'Elastic Mesh',
      'Animated Content',
      'Antigravity',
      'Blob Cursor',
      'Click Spark',
      'Crosshair',
      'Cubes',
      'Cursor Grid',
      'Electric Border',
      'Fade Content',
      'Ghost Cursor',
      'Glare Hover',
      'Gradual Blur',
      'Image Trail',
      'Laser Flow',
      'Logo Loop',
      'Magic Rings',
      'Magnet',
      'Magnet Lines',
      'Meta Balls',
      'Metallic Paint',
      'Noise',
      'Orbit Images',
      'Pixel Trail',
      'Pixel Transition',
      'Ribbons',
      'Shape Blur',
      'Splash Cursor',
      'Star Border',
      'Sticker Peel',
      'Strands',
      'Target Cursor'
    ]
  },
  {
    name: 'Micro',
    subcategories: [
      'Shredder',
      'Paper Crumple',
      'Warm Tooltip',
      'Wake Slider',
      'Voice Pill',
      'Thought Line',
      'Tear Ticket',
      'Swipe Toast',
      'Swipe Row',
      'Status Mark',
      'Squish Switch',
      'Spring Check',
      'Slosh Gauge',
      'Sling Button',
      'Slide Commit',
      'Scrub Field',
      'Rubber Segment',
      'Refine Frame',
      'Pulse Heart',
      'Prompt Bar',
      'Peek Rating',
      'Lattice Loader',
      'Jelly Radio',
      'Hold Button',
      'Glide Select',
      'Fuse Button',
      'Folder Float',
      'Flip Card',
      'Dodge Field',
      'Comet Dial',
      'Code Slots',
      'Call Chip',
      'Branched Menu',
      'Bell Toggle'
    ]
  },
  {
    name: 'Components',
    subcategories: [
      'Flex Carousel',
      'Infinite Spiral',
      'Morph Slider',
      'Drift Wall',
      'Depth Carousel',
      'Accordion Gallery',
      'Animated List',
      'Border Glow',
      'Bounce Cards',
      'Bubble Menu',
      'Card Nav',
      'Card Swap',
      'Carousel',
      'Chroma Grid',
      'Circular Gallery',
      'Curved Input',
      'Counter',
      'Decay Card',
      'Dock',
      'Dome Gallery',
      'Elastic Slider',
      'Flowing Menu',
      'Flying Posters',
      'Folder',
      'Glass Icons',
      'Glass Surface',
      'Gooey Nav',
      'Infinite Menu',
      'Line Sidebar',
      'Magic Bento',
      'Masonry',
      'Model Viewer',
      'Option Wheel',
      'Pill Nav',
      'Pixel Card',
      'Profile Card',
      'Reflective Card',
      'Scroll Stack',
      'Specular Button',
      'Spotlight Card',
      'Stack',
      'Staggered Menu',
      'Stepper',
      'Tilted Card'
    ]
  },
  {
    name: 'Backgrounds',
    subcategories: [
      'Micro Slats',
      'Scanner',
      'Shape Waves',
      'Ghost Fibers',
      'Aero Shards',
      'CRT Warp',
      'Web Threads',
      'Topography',
      'Sliced Waves',
      'Molten Metal',
      'Light Tunnel',
      'Gradient Waves',
      'Acid Squares',
      'Aurora',
      'Balatro',
      'Ballpit',
      'Beams',
      'Color Bends',
      'Dark Veil',
      'Dither',
      'Dot Field',
      'Dot Grid',
      'Evil Eye',
      'Faulty Terminal',
      'Ferrofluid',
      'Floating Lines',
      'Galaxy',
      'Gradient Blinds',
      'Grainient',
      'Grid Distortion',
      'Grid Motion',
      'Grid Scan',
      'Hyperspeed',
      'Iridescence',
      'Letter Glitch',
      'Light Pillar',
      'Light Rays',
      'Lightfall',
      'Lightning',
      'Line Waves',
      'Liquid Chrome',
      'Liquid Ether',
      'Orb',
      'Particles',
      'Pixel Blast',
      'Pixel Snow',
      'Plasma',
      'Plasma Wave',
      'Prism',
      'Prismatic Burst',
      'Radar',
      'Ripple Grid',
      'Shape Grid',
      'Side Rays',
      'Silk',
      'Soft Aurora',
      'Threads',
      'Waves'
    ]
  }
];

export const TOTAL_COMPONENTS = CATEGORIES.filter(category => category.name !== 'Get Started').reduce(
  (total, category) => total + category.subcategories.length,
  0
);

// Slug helpers (kebab-case used in URLs).
export const slug = (s: string) => s.replace(/\s+/g, '-').toLowerCase();
export const decodeLabel = (s: string) =>
  s
    .split('-')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
